[target.thumbv7em-none-eabihf]
runner = "cargo objcopy --release -- -O binary"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

[alias]
build-bin = "objcopy --release -- -O binary"